/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionconguis;

import java.awt.event.ActionEvent;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class GUIEstudiante extends GUIPersona {

    /**
     * Creates new form GUIEstudiante
     */
    public GUIEstudiante() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIEstudiante().setVisible(true);
            }
        });
    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource() == jBAgregar) {
            Estudiante p = new Estudiante(JOptionPane.showInputDialog(
                            rootPane, "Ingrese la carrera del nuevo estudiante"), 
                    JOptionPane.showInputDialog(rootPane, "Ingrese el año de ingreso del nuevo estudiante"),
                    JOptionPane.showInputDialog(rootPane, "Ingrese "
                    + "el nombre del nuevo estudiante"), JOptionPane.showInputDialog(
                            rootPane, "Ingrese el apellido del nuevo estudiante"),
                    JOptionPane.showInputDialog(rootPane, "Ingrese el rut del nuevo estudiante"));
            personas.add(p);
            ((DefaultListModel) jList1.getModel()).addElement(p);
        } else if (e.getSource() == jBBuscar) {
            String[] list = {"Nombre", "Apellido", "Rut","Carrera","Año de Ingreso"};
            JComboBox jcb = new JComboBox(list);
            JOptionPane.showMessageDialog(null, jcb, "Seleccione el tipo de dato a buscar", JOptionPane.QUESTION_MESSAGE);
            String search = JOptionPane.showInputDialog(rootPane, "Dato de busqueda");
            boolean found = false;
            switch (jcb.getSelectedItem().toString()) {
                case "Nombre":
                    for (int i = 0; i < personas.size(); i++) {
                        if (personas.get(i).getNombre().equals(search)) {
                            if (!found) {
                                model.removeAllElements();
                            }
                            model.addElement(personas.get(i));
                            found = true;
                        }
                    }
                    break;

                case "Apellido":
                    for (int i = 0; i < personas.size(); i++) {
                        if (personas.get(i).getApellido().equals(search)) {
                            if (!found) {
                                model.removeAllElements();
                            }
                            model.addElement(personas.get(i));
                            found = true;
                        }
                    }
                    break;

                case "Rut":
                    for (int i = 0; i < personas.size(); i++) {
                        if (personas.get(i).getRut().equals(search)) {
                            if (!found) {
                                model.removeAllElements();
                            }
                            model.addElement(personas.get(i));
                            found = true;
                        }
                    }
                    break;
                    
                case "Carrera":
                    for (int i = 0; i < personas.size(); i++) {
                        Estudiante aux = (Estudiante)personas.get(i);
                        if (aux.getCarrera().equals(search)) {
                            if (!found) {
                                model.removeAllElements();
                            }
                            model.addElement(personas.get(i));
                            found = true;
                        }
                    }
                    break;

                case "Año de Ingreso":
                    for (int i = 0; i < personas.size(); i++) {
                        Estudiante aux = (Estudiante)personas.get(i);
                        if (aux.getAñoIngreso().equals(search)) {
                            if (!found) {
                                model.removeAllElements();
                            }
                            model.addElement(personas.get(i));
                            found = true;
                        }
                    }
                    break;

            }
            if (found) {
                JOptionPane.showMessageDialog(rootPane, "Encontradas " + model.size() + " coincidencias");
            }
        } else if (e.getSource() == jBEliminar) {
            personas.remove(model.getElementAt(jList1.getSelectedIndex()));
            model.remove(jList1.getSelectedIndex());
        } else if (e.getSource() == jBMostarTodo) {
            model.removeAllElements();
            for (Persona p : personas) {
                model.addElement(p);
            }
        } else if (e.getSource() == jBMostrarDatos) {
            Estudiante aux = (Estudiante) model.getElementAt(jList1.getSelectedIndex());
            JOptionPane.showMessageDialog(rootPane, "La persona tienes estos datos: \n"
                + aux.getNombre() + " " + aux.getApellido() + "\n"
                + "RUT:" + aux.getRut()+"\n"
                        + "Carrera:"+aux.getCarrera()+"\n"
                                + "Año de Ingreso:"+aux.getAñoIngreso());
        }
    }  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
